### ISSUE TITLE
Cannot import already existing documents into Elastic App Search.

### ISSUE THREAD

**Issue by maruldy** [elastic/app-search-firestore-extension#37]
In the process of importing already existing documents into elastic app search, I met the error below.
It probably happens when there is so many existing data, would you tell me how to handle pagination?
if my prediction is wrong, please let me know.

```
Importing all documents from collection TestItem
Error retrieving documents for collection TestItem
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old.
    at Object.callErrorFromStatus (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@grpc/grpc-js/build/src/client.js:331:49)
    at Object.onReceiveStatus (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Caused by: Error
    at CollectionGroup._get (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@google-cloud/firestore/build/src/reference.js:1519:23)
    at CollectionGroup.get (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@google-cloud/firestore/build/src/reference.js:1507:21)
    at main (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@elastic/app-search-firestore-extension/lib/bin/import.js:23:79)
    at Object.<anonymous> (/Users/anony/.npm/_npx/11cf0a7e07b5396a/node_modules/@elastic/app-search-firestore-extension/lib/bin/import.js:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 9,
  details: 'The requested snapshot version is too old.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
```

**Comment by IchordeDionysos** [comment]
The script is NOT built for lots of data:
https://github.com/elastic/app-search-firestore-extension/blob/master/functions/src/bin/import.ts#L34

It essentially tries to download all data at once in one go and then upload them in batches!
https://github.com/elastic/app-search-firestore-extension/blob/master/functions/src/bin/import.ts#L50

Also, there should be a way that after each batch a snapshot file is written, so that if the process gets killed or aborted it can get picked up from where it was stopped.
